# Default packit instance is a prod and only this is used
# stg instance is present for testing new packit features in forked repositories where stg is installed.
packit_instances: ["prod"]
upstream_project_url: https://github.com/Lorquas/rhc
# issue_repository: https://github.com/strimzi/strimzi-kafka-operator
jobs:
  - job: tests
    trigger: pull_request
    # Suffix for job name
    identifier: "unit"
    targets:
      # https://packit.dev/docs/configuration/#aliases
      - centos-stream-9-x86_64
      - fedora-latest-stable
      # http://storage.tft.osci.redhat.com/composes-production.html
      - RHEL-8-Updated
    use_internal_tf: True
    skip_build: true
    # manual_trigger: true
    labels:
      - unit
