# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/hhatto/autopep8
    rev: 'v2.0.4'
    hooks:
      - id: autopep8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.1
    hooks:
      - id: ruff
        args:
          - '--fix'
          - '--show-fixes'

  - repo: https://github.com/teemtee/tmt.git
    rev: 1.28.2
    hooks:
      - id: tmt-lint
        additional_dependencies:
          # Make sure we use fmf compatible with tmt
          # in the repo, not the 1.26.0 version.
          - "fmf>=1.3.0"
          - pint==0.20
